-- * Do "before turn" stuff
-- * check to see if you have a turn, if not, done
-- * check for end round (if not already ending):
--    may end if deed deck empty
--    must end if deck deck and hand empty
--    if end round, then done.
-- * Otherwise start turn:
--    * Rest or regular
--    * During either must play or discard at least one card
--      (excepton, hand empty, but have deed deck)
